### ISSUE TITLE
OpenWeatherMap provider object parsing error

### ISSUE THREAD

**Issue by Paxifixi** [survivingwithandroid/WeatherLib#18]
Hi,

it is possible that i found a small parsing bug by using the OpenWeatherMap provider?

File: OpenweathermapProvider.java
Method: getCurrentCondition
Line: weather.currentCondition.setPressure(getInt("pressure", mainObj));

This should be:
weather.currentCondition.setPressure(getFloat("pressure", mainObj));

Because the OpenweatherMap provider returns this value as float value:

Watch the pressure value in the example file below:

{"message":"like","cod":"200","count":1,"list":[{"id":5689557,"name":"Hazen","coord":{"lon":-101.625,"lat":47.3016},"main":{"temp":271.935,"temp_min":271.935,"temp_max":271.935,"pressure":960.51,"sea_level":1035.23,"grnd_level":960.51,"humidity":69},"dt":1421261739,"wind":{"speed":6.35,"deg":261.516},"sys":{"country":"United States of America"},"clouds":{"all":8},"weather":[{"id":800,"main":"Clear","description":"Sky is Clear","icon":"02d"}]}]}

**Comment by survivingwithandroid** [comment]
It will resolved in the next release. Thx

**Comment by Paxifixi** [comment]
I have to thank... :+1: any plans when it will be released?

**Comment by survivingwithandroid** [comment]
In the master branch the bug is fixed. Next week i will release a new version.
Thx
