### ISSUE TITLE
OpenWeatherMap API Key required

### ISSUE THREAD

**Issue by v1r0x** [survivingwithandroid/WeatherLib#35]
Since last week an API key for openweathermap is required: http://openweathermap.org/faq#error401

**Comment by v1r0x** [comment]
Sorry for the previous short description.
The problem is, that it worked last week without any errors and since the 9th of october I got

**Comment by survivingwithandroid** [comment]
The problem should be resolved in 1.5.9 just released.

**Comment by swapps** [comment]
hi, it still doesn't work, the api key isn't added when searching for city:

10-19 14:39:18.170: D/SwA(26713): Client [com.survivingwithandroid.weather.lib.client.volley.WeatherClientDefault@b31c86a]
10-19 14:39:18.336: E/Volley(26713): [3891] BasicNetwork.performRequest: Unexpected response code 401 for http://api.openweathermap.org/data/2.5/find?mode=json&type=like&q=Co

as you can see the apikey is missing in the url request﻿

**Comment by athkalia** [comment]
Problem still exists in 1.5.9, and it's in method getQueryCityURLByLocation in line 466 of the OpenweathermapProvider. It's missing the createAPPID() method in the end. So is the getQueryCityURLByCoord method as well.

**Comment by survivingwithandroid** [comment]
Check 1.6.0

**Comment by v1r0x** [comment]
But it will still throw a `WeatherLibException` but I think it should throw an `ApiKeyRequiredException`, because an API Key is required since last week.
