### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by KlausHans** [survivingwithandroid/WeatherLib#48]
The last commit was in November 2015 and the issues kept unanswered. So, i assume this project dead?
Unfortunately i got some issues with it. Somebody knows an alternative weather lib for Android?

**Comment by survivingwithandroid** [comment]
Hello, 
the project is still open but anyway i haven't found time to upgrade it. It is really a pitty because i think the project is still interesting, i'm planning to work on it again but at the moment i can't confirm the date of the next release.

**Comment by KlausHans** [comment]
Thank you very much for the reply! Yes, your project is still interesting. :)
